# 1. Parse the Vivino collection

Normalize the two collection rounds into vintage, parent-wine, grape, and award tables. Requires the original merged API responses in `data/raw/vivino/`. This notebook does not perform the later cross-source merge; see `docs/reproducibility.md`.

**Recorded outputs:** figures and metrics are preserved from the course project. They have not been regenerated with the reorganized code. Datasets and fitted models are not included.

In [ ]:
from pathlib import Path
import sys

# Locate the checkout whether Jupyter starts in the root or notebooks/.
PROJECT_ROOT = next(
    p for p in (Path.cwd(), *Path.cwd().parents)
    if (p / "pyproject.toml").is_file() and (p / "src/wine_quality").is_dir()
)
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))
from wine_quality.paths import RAW_DATA, INTERIM_DATA, PROCESSED_DATA, FIGURES

for folder in (FIGURES / "eda", FIGURES / "imputation", FIGURES / "models" / "shap"):
    folder.mkdir(parents=True, exist_ok=True)

(INTERIM_DATA / "vivino").mkdir(parents=True, exist_ok=True)

## Phase 2: Parsing the scrapped data

#### files with datas
- all_merged_round1.json  : wine info from wines explore pages
- all_merged_round2.json  : wine info from other vintages years, used winery
- winery_merged.json      : winery ids and info, needed to get other vintages years
- /countries              : files that contains scrapped info from explore pages, with filters

We will use all_merged* files to get all of the wines info, clean the data (remove useless data) and save under csv

In [1]:
import json
import pandas as pd
import numpy as np
from pathlib import Path

### Extracting first round of data (~35 000 wines)

In [2]:
file = RAW_DATA / "vivino/all_merged_round1.json"

In [3]:
with open(file) as f:
    raw_js_wines = json.load(f)

In [10]:
raw_js_wines.keys(), len(raw_js_wines['vintage'])

(dict_keys(['vintage']), 35146)

In [ ]:
# structure of a wine
raw_js_wines['vintage'][0].keys()

dict_keys(['id', 'seo_name', 'name', 'statistics', 'organic_certification_id', 'certified_biodynamic', 'image', 'wine', 'description', 'wine_critic_reviews', 'awards', 'ratings_distribution', 'ranking', 'recommended_drinking_window', 'wine_facts', 'winemaker', 'wine_maker', 'grape_composition', 'year', 'grapes', 'has_valid_ratings'])

In [36]:
raw_js_wines['vintage'][0]["has_valid_ratings"]

True

In [39]:
# Revelent keys to keep

# seo_name/name, which to keep ?
# wine is about the general wine without taking account the years
# might need award?  see if keep
# has_valid_rating see if keep

keep_keys = ['id', "seo_name", "name", "statistics", "certified_biodynamic", "wine", "description", "awards", "ratings_distribution","ranking", "recommended_drinking_window", 
            "wine_facts", "grape_composition", "year", "grapes", "has_valid_ratings"]

# Keys not to keep

# organic certification id: need to have access to that
# image : bunch of urls
# wine_critic_reviews : gives only critics
# winemaker: no need for it
# wine_maker: no need for it

In [38]:
raw_wines = raw_js_wines['vintage']

In [43]:
raw_filtered_wines = [{k: wine[k] for k in keep_keys} for wine in raw_wines]

In [45]:
raw_filtered_wines[0].keys()

dict_keys(['id', 'seo_name', 'name', 'statistics', 'certified_biodynamic', 'wine', 'description', 'awards', 'ratings_distribution', 'ranking', 'recommended_drinking_window', 'wine_facts', 'grape_composition', 'year', 'grapes', 'has_valid_ratings'])

#### temporarily saving

In [46]:
with open(INTERIM_DATA / "vivino/filtered_wines_round1.json", "w") as f:
    json.dump(raw_filtered_wines, f, indent=2)

In [270]:
with open(INTERIM_DATA / "vivino/filtered_wines_round1.json") as f:
    round1 = json.load(f)

In [273]:
df_round1 = pd.DataFrame(round1)

#### saving for round 2

In [51]:
file2 = RAW_DATA / "vivino/all_merged_round2.json"

In [52]:
with open(file2) as f:
    raw_js_wines2 = json.load(f)

In [53]:
raw_wines2 = raw_js_wines2['vintage']
raw_filtered_wines2 = [{k: wine[k] for k in keep_keys} for wine in raw_wines2]

In [54]:
with open(INTERIM_DATA / "vivino/filtered_wines_round2.json", "w") as f:
    json.dump(raw_filtered_wines2, f, indent=2)

## CSV parsing

In [ ]:
# in the structure, there are references to ids, separate into many tables
# wine id
# grape id
# winery

In [71]:
df_round1 = pd.DataFrame(raw_filtered_wines)

Cols to split:
- wine
- ratings_distribution -> liste [1, 2, 3, 4, 5] stars

In [274]:
df_round1

,id,seo_name,name,statistics,certified_biodynamic,wine,description,awards,ratings_distribution,ranking,recommended_drinking_window,wine_facts,grape_composition,year,grapes,has_valid_ratings
0,100015094,chateau-mouton-rothschild-aile-d-argent-blanc-...,Château Mouton Rothschild Aile d'Argent Blanc ...,"{'status': 'Normal', 'ratings_count': 381, 'ra...",False,"{'id': 2284844, 'name': 'Aile d'Argent Blanc B...",,[],"{'1': 3, '2': 3, '3': 67, '4': 246, '5': 62}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'oak_aged': 0, 'certified_bi...","{'17': 0, '18': 0}",2016,"[{'id': 17, 'name': 'Sauvignon Blanc', 'seo_na...",True
1,10013618,reynvaan-the-classic-estate-cabernet-sauvignon...,Reynvaan The Classic Estate Cabernet Sauvignon...,"{'status': 'BelowThreshold', 'ratings_count': ...",None,"{'id': 2369586, 'name': 'The Classic Estate Ca...",,[],"{'1': 0, '2': 2, '3': 8, '4': 8, '5': 3}",{'country': {'description': 'Rank within Unite...,"{'start_year': 2015, 'end_year': 2028, 'status...",{},{},2013,None,False
2,10023048,j-m-gremillet-blanc-de-blancs-brut-champagne-nv,Gremillet Blanc de Blancs Brut Champagne,"{'status': 'Normal', 'ratings_count': 486, 'ra...",None,"{'id': 2714706, 'name': 'Blanc de Blancs Brut ...",,"[{'ID': 35171, 'CompetitionID': 1, 'VintageID'...","{'1': 5, '2': 10, '3': 161, '4': 270, '5': 40}",{'country': {'description': 'Rank within Franc...,"{'start_year': None, 'end_year': None, 'status...","{'alcohol': 12.5, 'residual_sugar_grams_per_li...",{'5': 100},N.V.,"[{'id': 5, 'name': 'Chardonnay', 'seo_name': '...",True
3,10027177,deutz-blanc-de-blancs-brut-champagne-2013,Deutz Blanc de Blancs Brut Champagne 2013,"{'status': 'Normal', 'ratings_count': 373, 'ra...",None,"{'id': 1142211, 'name': 'Blanc de Blancs Brut ...",,[],"{'1': 0, '2': 2, '3': 57, '4': 274, '5': 40}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2015, 'end_year': 2028, 'status...",{'alcohol': 12.5},{'5': 100},2013,"[{'id': 5, 'name': 'Chardonnay', 'seo_name': '...",True
4,100451553,livon-selezione-anniversario-2014,Livon Selezione Anniversario 2014,"{'status': 'Normal', 'ratings_count': 25, 'rat...",None,"{'id': 4153013, 'name': 'Selezione Anniversari...",,[],"{'1': 0, '2': 0, '3': 3, '4': 19, '5': 3}",{'country': {'description': 'Rank within Italy...,"{'start_year': 2016, 'end_year': 2024, 'status...",{'alcohol': 13.5},{},2014,None,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35141,99616661,chateau-du-haut-pick-sauternes-2014,Château du Haut Pick Sauternes 2014,"{'status': 'Normal', 'ratings_count': 42, 'rat...",None,"{'id': 1834572, 'name': 'Sauternes', 'seo_name...",,[],"{'1': 1, '2': 2, '3': 24, '4': 11, '5': 4}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2034, 'status...",{},{},2014,None,True
35142,9986182,domaine-perrot-minot-vignes-centenaires-nuits-...,Domaine Perrot-Minot Vignes Centenaires Nuits-...,"{'status': 'Normal', 'ratings_count': 43, 'rat...",None,"{'id': 2711130, 'name': 'Vignes Centenaires Nu...",,[],"{'1': 0, '2': 1, '3': 0, '4': 31, '5': 11}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2014, 'end_year': 2028, 'status...",{},{},2012,None,True
35143,99861,fr-chateau-pape-clement-pessac-leognan-grand-c...,Château Pape Clément Pessac-Léognan (Grand Cru...,"{'status': 'Normal', 'ratings_count': 1641, 'r...",None,"{'id': 82613, 'name': 'Pessac-Léognan (Grand C...",The grapes are initially sorted in the vineyar...,[],"{'1': 9, '2': 13, '3': 127, '4': 1012, '5': 480}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2011, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'residual_sugar_grams_per_li...",{},2006,None,True
35144,99949,biondi-santi-brunello-di-montalcino-riserva-2001,Biondi-Santi Brunello di Montalcino Riserva 2001,"{'status': 'Normal', 'ratings_count': 154, 'ra...",None,"{'id': 82698, 'name': 'Brunello di Montalcino ...",,[],"{'1': 0, '2': 3, '3': 9, '4': 65, '5': 77}",{'country': {'description': 'Rank within Italy...,"{'start_year': 2011, 'end_year': 2028, 'status...","{'alcohol': 14, 'contains_sulfites_allergens':...",{'16': 100},2001,"[{'id': 16, 'name': 'Sangiovese', 'seo_name': ...",True
35145,9997820,domaine-cazes-muscat-de-rivesaltes-vin-doux-na...,Cazes Muscat de Rivesaltes Vin Doux Naturel 1991,"{'status': 'BelowThreshold', 'ratings_count': ...",None,"{'id': 20225, 'name': 'Muscat de Rivesaltes Vi...",,[],"{'1': 0, '2': 0, '3': 0, '4': 3, '5': 1}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2001, 'end_year': 2026, 'status...",{'contains_sulfites_allergens': True},{},1991,None,False

In [275]:
# table of grapes
grapes1 = df_round1['grapes'].values

In [ ]:
grapes1 = [[element[i] for i in range(len(element))] for element in grapes1 if element]

In [278]:
grapes1 = [el for sub in grapes1 for el in sub  if sub]

In [280]:
df_grapes1 = pd.DataFrame(grapes1)

In [281]:
df_grapes1 = df_grapes1.drop_duplicates()
df_grapes1

,id,name,seo_name,has_detailed_info,wines_count,parent_grape_id
0,17,Sauvignon Blanc,sauvignon-blanc,True,292440,NaN
1,18,Sémillon,semillion,True,65710,NaN
2,5,Chardonnay,chardonnay,True,604208,NaN
4,19,Tempranillo,tempranillo,True,172842,NaN
6,199,Pinot Nero,pinot-nero,False,16533,14.0
...,...,...,...,...,...,...
11545,245,Picpoul Blanc,picpoul-blanc,False,3522,NaN
11557,982,Fortana,fortana,False,183,NaN
11577,1551,Trebbiano D'Abruzzo,trebbiano-d-abruzzo,False,1905,NaN
11721,566,Morenillo,morenillo,False,159,NaN
12051,370,Vespaiola,vespaiola,False,425,NaN

In [282]:
# save table
df_grapes1.to_csv(INTERIM_DATA / "vivino/grapes1_df.csv", index=False)

In [284]:
# split col grapes
l = df_round1['grapes'].values
l = [[el[i]["id"] for i in range(len(el))] if el else np.nan for el in l]
df_round1['grapes'] = l

In [285]:
# table of wine (parent)
wine1 = df_round1["wine"].values
wine1

array([{'id': 2284844, 'name': "Aile d'Argent Blanc Bordeaux", 'seo_name': 'aile-d-argent-blanc-bordeaux', 'type_id': 2, 'vintage_type': 0, 'is_natural': False, 'region': {'id': 383, 'name': 'Bordeaux', 'name_en': '', 'seo_name': 'bordeaux', 'country': {'code': 'fr', 'name': 'France', 'native_name': 'France', 'seo_name': 'france', 'currency': {'code': 'EUR', 'name': 'Euros', 'prefix': '€', 'suffix': None}, 'regions_count': 1309, 'users_count': 7235204, 'wines_count': 452623, 'wineries_count': 69083, 'most_used_grapes': [{'id': 14, 'name': 'Pinot Noir', 'seo_name': 'pinot-noir', 'has_detailed_info': True, 'wines_count': 572334, 'parent_grape_id': None}, {'id': 5, 'name': 'Chardonnay', 'seo_name': 'chardonnay', 'has_detailed_info': True, 'wines_count': 604208, 'parent_grape_id': None}, {'id': 10, 'name': 'Merlot', 'seo_name': 'merlot', 'has_detailed_info': True, 'wines_count': 566719, 'parent_grape_id': None}]}, 'parent_id': None, 'background_image': {'location': '//images.vivino.com/regions/backgrounds/3z0tiBnOSPaSk5LxoYKRYg.jpeg', 'variations': {'large': '//thumbs.vivino.com/region_backgrounds/3z0tiBnOSPaSk5LxoYKRYg_1280x760.jpeg', 'medium': '//thumbs.vivino.com/region_backgrounds/3z0tiBnOSPaSk5LxoYKRYg_600x356.jpeg'}}, 'class': 'VivinoAPI::Region', 'statistics': {'wineries_count': 13250, 'wines_count': 42428, 'sub_regions_count': 0, 'parent_regions_count': 0}}, 'vintage_mask': ['2025'], 'review_status': 2, 'winery': {'id': 64252, 'name': 'Château Mouton Rothschild', 'seo_name': 'chateau-mouton-rothschild', 'status': 0, 'review_status': 'Completed', 'background_image': None, 'statistics': {'ratings_count': 104754, 'ratings_average': 4.5, 'labels_count': 1064257, 'wines_count': 7}}, 'statistics': {'status': 'Normal', 'ratings_count': 5640, 'ratings_average': 4.3, 'labels_count': 41773, 'vintages_count': 90}, 'rank': None, 'hidden': False, 'vintages': [{'id': 180178974, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2024', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2024", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 2, 'ratings_average': 0, 'labels_count': 1, 'reviews_count': 1}, 'year': 2024, 'grapes': None, 'has_valid_ratings': False}, {'id': 174051416, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2023', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2023", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 5, 'ratings_average': 0, 'labels_count': 23, 'reviews_count': 3}, 'year': 2023, 'grapes': None, 'has_valid_ratings': False}, {'id': 170526870, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2022', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2022", 'statistics': {'status': 'Normal', 'ratings_count': 50, 'ratings_average': 4.3, 'labels_count': 188, 'reviews_count': 19}, 'year': 2022, 'grapes': None, 'has_valid_ratings': True}, {'id': 171362101, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2021', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2021", 'statistics': {'status': 'Normal', 'ratings_count': 91, 'ratings_average': 4.2, 'labels_count': 547, 'reviews_count': 31}, 'year': 2021, 'grapes': None, 'has_valid_ratings': True}, {'id': 163696405, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2020', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2020", 'statistics': {'status': 'Normal', 'ratings_count': 151, 'ratings_average': 4.2, 'labels_count': 1167, 'reviews_count': 52}, 'year': 2020, 'grapes': None, 'has_valid_ratings': True}, {'id': 160205309, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2019', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2019", 'statistics': {'status': 'Normal', 'ratings_count': 324, 'ratings_average': 4.4, 'labels_count': 2368, 'reviews_count': 112}, 'year': 2019, 'grapes': None, 'has_valid_ratings': True}, {'id': 156153271, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2018', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2018", 'statistics': {'status': 'Normal', 'ratings_count': 300, 'ratings_average': 4.4, 'labels_count': 2390, 'reviews_count': 119}, 'year': 2018, 'grapes': None, 'has_valid_ratings': True}, {'id': 150603471, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2017', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2017", 'statistics': {'status': 'Normal', 'ratings_count': 426, 'ratings_average': 4.3, 'labels_count': 3034, 'reviews_count': 184}, 'year': 2017, 'grapes': None, 'has_valid_ratings': True}, {'id': 100015094, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2016', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2016", 'statistics': {'status': 'Normal', 'ratings_count': 381, 'ratings_average': 4.2, 'labels_count': 3397, 'reviews_count': 148}, 'year': 2016, 'grapes': None, 'has_valid_ratings': True}, {'id': 19268538, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2015', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2015", 'statistics': {'status': 'Normal', 'ratings_count': 411, 'ratings_average': 4.3, 'labels_count': 3013, 'reviews_count': 163}, 'year': 2015, 'grapes': None, 'has_valid_ratings': True}, {'id': 4309647, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2014', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2014", 'statistics': {'status': 'Normal', 'ratings_count': 357, 'ratings_average': 4.2, 'labels_count': 2561, 'reviews_count': 117}, 'year': 2014, 'grapes': None, 'has_valid_ratings': True}, {'id': 5144180, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2013', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2013", 'statistics': {'status': 'Normal', 'ratings_count': 435, 'ratings_average': 4.3, 'labels_count': 3055, 'reviews_count': 169}, 'year': 2013, 'grapes': None, 'has_valid_ratings': True}, {'id': 6094083, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2012', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2012", 'statistics': {'status': 'Normal', 'ratings_count': 322, 'ratings_average': 4.2, 'labels_count': 2265, 'reviews_count': 123}, 'year': 2012, 'grapes': None, 'has_valid_ratings': True}, {'id': 4687648, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2011', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2011", 'statistics': {'status': 'Normal', 'ratings_count': 306, 'ratings_average': 4.2, 'labels_count': 2137, 'reviews_count': 109}, 'year': 2011, 'grapes': None, 'has_valid_ratings': True}, {'id': 6800421, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2010', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2010", 'statistics': {'status': 'Normal', 'ratings_count': 243, 'ratings_average': 4.1, 'labels_count': 1578, 'reviews_count': 76}, 'year': 2010, 'grapes': None, 'has_valid_ratings': True}, {'id': 4974105, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2009', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2009", 'statistics': {'status': 'Normal', 'ratings_count': 248, 'ratings_average': 4, 'labels_count': 1864, 'reviews_count': 82}, 'year': 2009, 'grapes': None, 'has_valid_ratings': True}, {'id': 4628450, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2008', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2008", 'statistics': {'status': 'Normal', 'ratings_count': 224, 'ratings_average': 4.2, 'labels_count': 1330, 'reviews_count': 76}, 'year': 2008, 'grapes': None, 'has_valid_ratings': True}, {'id': 1359541, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2007', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2007", 'statistics': {'status': 'Normal', 'ratings_count': 102, 'ratings_average': 4, 'labels_count': 814, 'reviews_count': 24}, 'year': 2007, 'grapes': None, 'has_valid_ratings': True}, {'id': 5481351, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2006', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2006", 'statistics': {'status': 'Normal', 'ratings_count': 150, 'ratings_average': 4.3, 'labels_count': 1089, 'reviews_count': 42}, 'year': 2006, 'grapes': None, 'has_valid_ratings': True}, {'id': 23230, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2005', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2005", 'statistics': {'status': 'Normal', 'ratings_count': 124, 'ratings_average': 4, 'labels_count': 990, 'reviews_count': 35}, 'year': 2005, 'grapes': None, 'has_valid_ratings': True}, {'id': 9490204, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2004', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2004", 'statistics': {'status': 'Normal', 'ratings_count': 61, 'ratings_average': 4.3, 'labels_count': 424, 'reviews_count': 18}, 'year': 2004, 'grapes': None, 'has_valid_ratings': True}, {'id': 5069986, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2003', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2003", 'statistics': {'status': 'Normal', 'ratings_count': 42, 'ratings_average': 4.1, 'labels_count': 378, 'reviews_count': 14}, 'year': 2003, 'grapes': None, 'has_valid_ratings': True}, {'id': 6597647, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2002', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2002", 'statistics': {'status': 'Normal', 'ratings_count': 98, 'ratings_average': 4.4, 'labels_count': 973, 'reviews_count': 31}, 'year': 2002, 'grapes': None, 'has_valid_ratings': True}, {'id': 5998083, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2001', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2001", 'statistics': {'status': 'Normal', 'ratings_count': 28, 'ratings_average': 4, 'labels_count': 207, 'reviews_count': 8}, 'year': 2001, 'grapes': None, 'has_valid_ratings': True}, {'id': 1545661, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-2000', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 2000", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 22, 'ratings_average': 0, 'labels_count': 192, 'reviews_count': 7}, 'year': 2000, 'grapes': None, 'has_valid_ratings': False}, {'id': 2234355, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1999', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1999", 'statistics': {'status': 'Normal', 'ratings_count': 30, 'ratings_average': 4.3, 'labels_count': 338, 'reviews_count': 12}, 'year': 1999, 'grapes': None, 'has_valid_ratings': True}, {'id': 5123937, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1998', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1998", 'statistics': {'status': 'Normal', 'ratings_count': 53, 'ratings_average': 4.6, 'labels_count': 405, 'reviews_count': 17}, 'year': 1998, 'grapes': None, 'has_valid_ratings': True}, {'id': 7467012, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1997', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1997", 'statistics': {'status': 'Normal', 'ratings_count': 34, 'ratings_average': 4.2, 'labels_count': 324, 'reviews_count': 11}, 'year': 1997, 'grapes': None, 'has_valid_ratings': True}, {'id': 10053537, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1996', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1996", 'statistics': {'status': 'Normal', 'ratings_count': 32, 'ratings_average': 4.2, 'labels_count': 249, 'reviews_count': 13}, 'year': 1996, 'grapes': None, 'has_valid_ratings': True}, {'id': 8871688, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1995', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1995", 'statistics': {'status': 'Normal', 'ratings_count': 30, 'ratings_average': 4.3, 'labels_count': 306, 'reviews_count': 14}, 'year': 1995, 'grapes': None, 'has_valid_ratings': True}, {'id': 2956455, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1994', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1994", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 21, 'ratings_average': 0, 'labels_count': 226, 'reviews_count': 6}, 'year': 1994, 'grapes': None, 'has_valid_ratings': False}, {'id': 1573396, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1993', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1993", 'statistics': {'status': 'Normal', 'ratings_count': 99, 'ratings_average': 4.3, 'labels_count': 779, 'reviews_count': 32}, 'year': 1993, 'grapes': None, 'has_valid_ratings': True}, {'id': 1298244, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1992', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1992", 'statistics': {'status': 'Normal', 'ratings_count': 31, 'ratings_average': 4.2, 'labels_count': 211, 'reviews_count': 9}, 'year': 1992, 'grapes': None, 'has_valid_ratings': True}, {'id': 1693853, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1991', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1991", 'statistics': {'status': 'Normal', 'ratings_count': 34, 'ratings_average': 3.9, 'labels_count': 174, 'reviews_count': 12}, 'year': 1991, 'grapes': None, 'has_valid_ratings': True}, {'id': 1545339, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1990', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1990", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 20, 'ratings_average': 0, 'labels_count': 326, 'reviews_count': 4}, 'year': 1990, 'grapes': None, 'has_valid_ratings': False}, {'id': 1852706, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1989', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1989", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 10, 'ratings_average': 0, 'labels_count': 191, 'reviews_count': 1}, 'year': 1989, 'grapes': None, 'has_valid_ratings': False}, {'id': 2205608, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1988', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1988", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 17, 'ratings_average': 0, 'labels_count': 149, 'reviews_count': 6}, 'year': 1988, 'grapes': None, 'has_valid_ratings': False}, {'id': 1765233, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1987', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1987", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 12, 'ratings_average': 0, 'labels_count': 88, 'reviews_count': 3}, 'year': 1987, 'grapes': None, 'has_valid_ratings': False}, {'id': 10053017, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1986', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1986", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 5, 'ratings_average': 0, 'labels_count': 56, 'reviews_count': 1}, 'year': 1986, 'grapes': None, 'has_valid_ratings': False}, {'id': 2391993, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1985', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1985", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 1, 'ratings_average': 0, 'labels_count': 26, 'reviews_count': 0}, 'year': 1985, 'grapes': None, 'has_valid_ratings': False}, {'id': 2457255, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1983', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1983", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 3, 'ratings_average': 0, 'labels_count': 21, 'reviews_count': 2}, 'year': 1983, 'grapes': None, 'has_valid_ratings': False}, {'id': 6416877, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1982', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1982", 'statistics': {'status': 'Normal', 'ratings_count': 41, 'ratings_average': 4.6, 'labels_count': 582, 'reviews_count': 9}, 'year': 1982, 'grapes': None, 'has_valid_ratings': True}, {'id': 3154230, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1981', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1981", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 4, 'ratings_average': 0, 'labels_count': 11, 'reviews_count': 1}, 'year': 1981, 'grapes': None, 'has_valid_ratings': False}, {'id': 4309639, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1980', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1980", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 1, 'ratings_average': 0, 'labels_count': 4, 'reviews_count': 1}, 'year': 1980, 'grapes': None, 'has_valid_ratings': False}, {'id': 2894557, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1978', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1978", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 11, 'ratings_average': 0, 'labels_count': 67, 'reviews_count': 2}, 'year': 1978, 'grapes': None, 'has_valid_ratings': False}, {'id': 10461950, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1977', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1977", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 1, 'ratings_average': 0, 'labels_count': 9, 'reviews_count': 0}, 'year': 1977, 'grapes': None, 'has_valid_ratings': False}, {'id': 1577486, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1976', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1976", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 8, 'ratings_average': 0, 'labels_count': 72, 'reviews_count': 1}, 'year': 1976, 'grapes': None, 'has_valid_ratings': False}, {'id': 1544486, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1975', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1975", 'statistics': {'status': 'Normal', 'ratings_count': 47, 'ratings_average': 4.6, 'labels_count': 393, 'reviews_count': 13}, 'year': 1975, 'grapes': None, 'has_valid_ratings': True}, {'id': 1942971, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1973', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1973", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 2, 'ratings_average': 0, 'labels_count': 12, 'reviews_count': 0}, 'year': 1973, 'grapes': None, 'has_valid_ratings': False}, {'id': 1975554, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1972', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1972", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 3, 'ratings_average': 0, 'labels_count': 35, 'reviews_count': 0}, 'year': 1972, 'grapes': None, 'has_valid_ratings': False}, {'id': 8537053, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1971', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1971", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 5, 'ratings_average': 0, 'labels_count': 42, 'reviews_count': 0}, 'year': 1971, 'grapes': None, 'has_valid_ratings': False}, {'id': 1589864, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1970', 'name': "Château Mouton Rothschild Aile d'Argent Blanc Bordeaux 1970", 'statistics': {'status': 'BelowThreshold', 'ratings_count': 19, 'ratings_average': 0, 'labels_count': 197, 'reviews_count': 3}, 'year': 1970, 'grapes': None, 'has_valid_ratings': False}, {'id': 1558782, 'seo_name': 'chateau-mouton-rothschild-aile-d-argent-blanc-bordeaux-1969', 'name': "Château Mouton Rothschild Aile d'Argent Bl

In [286]:
df_wines1 = pd.json_normalize(wine1, sep='_')
df_wines1 = df_wines1.drop_duplicates(subset="id")
df_wines1

,id,name,seo_name,type_id,vintage_type,is_natural,vintage_mask,review_status,rank,hidden,...,style_region,style_region_background_image,specialists_notes,winery_dashboard_url,winery_background_image_location,winery_background_image_variations_large,winery_background_image_variations_medium,winery_background_image_variations_small,style_image_location,style
0,2284844,Aile d'Argent Blanc Bordeaux,aile-d-argent-blanc-bordeaux,2,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2369586,The Classic Estate Cabernet Sauvignon,the-classic-estate-cabernet-sauvignon,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2714706,Blanc de Blancs Brut Champagne,blanc-de-blancs-brut-champagne,3,1,False,[>0],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1142211,Blanc de Blancs Brut Champagne,blanc-de-blancs-brut-champagne,3,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4153013,Selezione Anniversario,selezione-anniversario,2,0,False,NaN,2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35110,2694726,Brut,brut,3,1,True,[>0],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35130,1203891,Cava AgustÍ-Vilaret Gran Reserva Extra Brut,cava-agusti-vilaret-gran-reserva-extra-brut,3,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35132,82079,The Complicator,the-complicator,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35133,82081,Left Field,left-field,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35139,1672879,Rioja Gran Reserva,rioja-gran-reserva,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [287]:
# save table
df_wines1.to_csv(INTERIM_DATA / "vivino/wines1_df.csv", index=False)

In [288]:
# split col wine
l = df_round1['wine']
l = [el["id"] if el else np.nan for el in l]
df_round1['wine'] = l

In [289]:
df_round1

,id,seo_name,name,statistics,certified_biodynamic,wine,description,awards,ratings_distribution,ranking,recommended_drinking_window,wine_facts,grape_composition,year,grapes,has_valid_ratings
0,100015094,chateau-mouton-rothschild-aile-d-argent-blanc-...,Château Mouton Rothschild Aile d'Argent Blanc ...,"{'status': 'Normal', 'ratings_count': 381, 'ra...",False,2284844,,[],"{'1': 3, '2': 3, '3': 67, '4': 246, '5': 62}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'oak_aged': 0, 'certified_bi...","{'17': 0, '18': 0}",2016,"[17, 18]",True
1,10013618,reynvaan-the-classic-estate-cabernet-sauvignon...,Reynvaan The Classic Estate Cabernet Sauvignon...,"{'status': 'BelowThreshold', 'ratings_count': ...",None,2369586,,[],"{'1': 0, '2': 2, '3': 8, '4': 8, '5': 3}",{'country': {'description': 'Rank within Unite...,"{'start_year': 2015, 'end_year': 2028, 'status...",{},{},2013,NaN,False
2,10023048,j-m-gremillet-blanc-de-blancs-brut-champagne-nv,Gremillet Blanc de Blancs Brut Champagne,"{'status': 'Normal', 'ratings_count': 486, 'ra...",None,2714706,,"[{'ID': 35171, 'CompetitionID': 1, 'VintageID'...","{'1': 5, '2': 10, '3': 161, '4': 270, '5': 40}",{'country': {'description': 'Rank within Franc...,"{'start_year': None, 'end_year': None, 'status...","{'alcohol': 12.5, 'residual_sugar_grams_per_li...",{'5': 100},N.V.,[5],True
3,10027177,deutz-blanc-de-blancs-brut-champagne-2013,Deutz Blanc de Blancs Brut Champagne 2013,"{'status': 'Normal', 'ratings_count': 373, 'ra...",None,1142211,,[],"{'1': 0, '2': 2, '3': 57, '4': 274, '5': 40}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2015, 'end_year': 2028, 'status...",{'alcohol': 12.5},{'5': 100},2013,[5],True
4,100451553,livon-selezione-anniversario-2014,Livon Selezione Anniversario 2014,"{'status': 'Normal', 'ratings_count': 25, 'rat...",None,4153013,,[],"{'1': 0, '2': 0, '3': 3, '4': 19, '5': 3}",{'country': {'description': 'Rank within Italy...,"{'start_year': 2016, 'end_year': 2024, 'status...",{'alcohol': 13.5},{},2014,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35141,99616661,chateau-du-haut-pick-sauternes-2014,Château du Haut Pick Sauternes 2014,"{'status': 'Normal', 'ratings_count': 42, 'rat...",None,1834572,,[],"{'1': 1, '2': 2, '3': 24, '4': 11, '5': 4}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2034, 'status...",{},{},2014,NaN,True
35142,9986182,domaine-perrot-minot-vignes-centenaires-nuits-...,Domaine Perrot-Minot Vignes Centenaires Nuits-...,"{'status': 'Normal', 'ratings_count': 43, 'rat...",None,2711130,,[],"{'1': 0, '2': 1, '3': 0, '4': 31, '5': 11}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2014, 'end_year': 2028, 'status...",{},{},2012,NaN,True
35143,99861,fr-chateau-pape-clement-pessac-leognan-grand-c...,Château Pape Clément Pessac-Léognan (Grand Cru...,"{'status': 'Normal', 'ratings_count': 1641, 'r...",None,82613,The grapes are initially sorted in the vineyar...,[],"{'1': 9, '2': 13, '3': 127, '4': 1012, '5': 480}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2011, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'residual_sugar_grams_per_li...",{},2006,NaN,True
35144,99949,biondi-santi-brunello-di-montalcino-riserva-2001,Biondi-Santi Brunello di Montalcino Riserva 2001,"{'status': 'Normal', 'ratings_count': 154, 'ra...",None,82698,,[],"{'1': 0, '2': 3, '3': 9, '4': 65, '5': 77}",{'country': {'description': 'Rank within Italy...,"{'start_year': 2011, 'end_year': 2028, 'status...","{'alcohol': 14, 'contains_sulfites_allergens':...",{'16': 100},2001,[16],True
35145,9997820,domaine-cazes-muscat-de-rivesaltes-vin-doux-na...,Cazes Muscat de Rivesaltes Vin Doux Naturel 1991,"{'status': 'BelowThreshold', 'ratings_count': ...",None,20225,,[],"{'1': 0, '2': 0, '3': 0, '4': 3, '5': 1}",{'country': {'description': 'Rank within Franc...,"{'start_year': 2001, 'end_year': 2026, 'status...",{'contains_sulfites_allergens': True},{},1991,NaN,False

In [290]:
# rating distributions
rat1 = df_round1['ratings_distribution']
rat1 = [[e[str(i)] for i in range(1, 6)] for e in rat1]
df_round1['ratings_distribution'] = rat1

In [291]:
df_round1

,id,seo_name,name,statistics,certified_biodynamic,wine,description,awards,ratings_distribution,ranking,recommended_drinking_window,wine_facts,grape_composition,year,grapes,has_valid_ratings
0,100015094,chateau-mouton-rothschild-aile-d-argent-blanc-...,Château Mouton Rothschild Aile d'Argent Blanc ...,"{'status': 'Normal', 'ratings_count': 381, 'ra...",False,2284844,,[],"[3, 3, 67, 246, 62]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'oak_aged': 0, 'certified_bi...","{'17': 0, '18': 0}",2016,"[17, 18]",True
1,10013618,reynvaan-the-classic-estate-cabernet-sauvignon...,Reynvaan The Classic Estate Cabernet Sauvignon...,"{'status': 'BelowThreshold', 'ratings_count': ...",None,2369586,,[],"[0, 2, 8, 8, 3]",{'country': {'description': 'Rank within Unite...,"{'start_year': 2015, 'end_year': 2028, 'status...",{},{},2013,NaN,False
2,10023048,j-m-gremillet-blanc-de-blancs-brut-champagne-nv,Gremillet Blanc de Blancs Brut Champagne,"{'status': 'Normal', 'ratings_count': 486, 'ra...",None,2714706,,"[{'ID': 35171, 'CompetitionID': 1, 'VintageID'...","[5, 10, 161, 270, 40]",{'country': {'description': 'Rank within Franc...,"{'start_year': None, 'end_year': None, 'status...","{'alcohol': 12.5, 'residual_sugar_grams_per_li...",{'5': 100},N.V.,[5],True
3,10027177,deutz-blanc-de-blancs-brut-champagne-2013,Deutz Blanc de Blancs Brut Champagne 2013,"{'status': 'Normal', 'ratings_count': 373, 'ra...",None,1142211,,[],"[0, 2, 57, 274, 40]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2015, 'end_year': 2028, 'status...",{'alcohol': 12.5},{'5': 100},2013,[5],True
4,100451553,livon-selezione-anniversario-2014,Livon Selezione Anniversario 2014,"{'status': 'Normal', 'ratings_count': 25, 'rat...",None,4153013,,[],"[0, 0, 3, 19, 3]",{'country': {'description': 'Rank within Italy...,"{'start_year': 2016, 'end_year': 2024, 'status...",{'alcohol': 13.5},{},2014,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35141,99616661,chateau-du-haut-pick-sauternes-2014,Château du Haut Pick Sauternes 2014,"{'status': 'Normal', 'ratings_count': 42, 'rat...",None,1834572,,[],"[1, 2, 24, 11, 4]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2034, 'status...",{},{},2014,NaN,True
35142,9986182,domaine-perrot-minot-vignes-centenaires-nuits-...,Domaine Perrot-Minot Vignes Centenaires Nuits-...,"{'status': 'Normal', 'ratings_count': 43, 'rat...",None,2711130,,[],"[0, 1, 0, 31, 11]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2014, 'end_year': 2028, 'status...",{},{},2012,NaN,True
35143,99861,fr-chateau-pape-clement-pessac-leognan-grand-c...,Château Pape Clément Pessac-Léognan (Grand Cru...,"{'status': 'Normal', 'ratings_count': 1641, 'r...",None,82613,The grapes are initially sorted in the vineyar...,[],"[9, 13, 127, 1012, 480]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2011, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'residual_sugar_grams_per_li...",{},2006,NaN,True
35144,99949,biondi-santi-brunello-di-montalcino-riserva-2001,Biondi-Santi Brunello di Montalcino Riserva 2001,"{'status': 'Normal', 'ratings_count': 154, 'ra...",None,82698,,[],"[0, 3, 9, 65, 77]",{'country': {'description': 'Rank within Italy...,"{'start_year': 2011, 'end_year': 2028, 'status...","{'alcohol': 14, 'contains_sulfites_allergens':...",{'16': 100},2001,[16],True
35145,9997820,domaine-cazes-muscat-de-rivesaltes-vin-doux-na...,Cazes Muscat de Rivesaltes Vin Doux Naturel 1991,"{'status': 'BelowThreshold', 'ratings_count': ...",None,20225,,[],"[0, 0, 0, 3, 1]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2001, 'end_year': 2026, 'status...",{'contains_sulfites_allergens': True},{},1991,NaN,False

In [292]:
l = df_round1["awards"].values
l = [subel for el in l for subel in el if subel]
l

[{'ID': 35171,
  'CompetitionID': 1,
  'VintageID': 10023048,
  'Edition': '2014',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2014/Wine/53202?name=Gremillet-Blanc%20de%20Blancs%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:44:26Z',
  'CreatedAt': '2021-01-13T09:15:58Z'},
 {'ID': 57122,
  'CompetitionID': 1,
  'VintageID': 10023048,
  'Edition': '2015',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2015/Wine/67124?name=Gremillet-Blanc%20de%20Blancs%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:49:52Z',
  'CreatedAt': '2021-01-13T09:20:34Z'},
 {'ID': 4175,
  'CompetitionID': 4,
  'VintageID': 10023048,
  'Edition': '2015',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.iwsc.net/result/detail/62445',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:36:26Z',
  'CreatedAt': '2021-01-15T17:33:33Z'},
 {'ID': 87134,
  'CompetitionID': 7,
  'VintageID': 10023048,
  'Edition': '2015',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DAWA/2015/Wine/76760?name=Gremillet-Blanc%20De%20Blancs%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:57:21Z',
  'CreatedAt': '2021-01-13T09:28:33Z'},
 {'ID': 93077,
  'CompetitionID': 7,
  'VintageID': 10023048,
  'Edition': '2017',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': '88',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DAWA/2017/Wine/406491?name=Gremillet-Blanc%20de%20Blancs%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:58:48Z',
  'CreatedAt': '2021-01-13T09:29:57Z'},
 {'ID': 55799,
  'CompetitionID': 5,
  'VintageID': 10335967,
  'Edition': '2017',
  'Medal': 'Excellent',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://www.hachette-vins.com/guide-vins/les-vins/f-amp-r-miniere-blanc-de-blancs-cuvee-blanc-absolu-vinifie-en-fut-de-chene-2017/201719394/',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:49:31Z',
  'CreatedAt': '2021-01-15T17:47:20Z'},
 {'ID': 154205,
  'CompetitionID': 1,
  'VintageID': 10588867,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': '90',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2017/Wine/392056?name=Abadia%20Retuerta-Selecci%C3%B3n%20Especial-2014',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:14:16Z',
  'CreatedAt': '2018-03-27T13:32:18Z'},
 {'ID': 129599,
  'CompetitionID': 2,
  'VintageID': 10588867,
  'Edition': '2017',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=113501',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:08:06Z',
  'CreatedAt': '2018-03-19T12:47:43Z'},
 {'ID': 105440,
  'CompetitionID': 10,
  'VintageID': 10588867,
  'Edition': '2017',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://results.concoursmondial.com/result_popup.php?id=107542',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:01:56Z',
  'CreatedAt': '2018-03-15T12:42:31Z'},
 {'ID': 45476,
  'CompetitionID': 1,
  'VintageID': 10764689,
  'Edition': '2015',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2015/Wine/66654?name=Devaux-Ultra%20D%20Extra%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:46:59Z',
  'CreatedAt': '2021-01-13T09:18:03Z'},
 {'ID': 62575,
  'CompetitionID': 5,
  'VintageID': 10915212,
  'Edition': '2017',
  'Medal': 'Remarkable',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://www.hachette-vins.com/guide-vins/les-vins/clos-de-la-coulee-de-serrant-2014-2017/201701119/',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:51:15Z',
  'CreatedAt': '2018-03-15T12:33:13Z'},
 {'ID': 126238,
  'CompetitionID': 2,
  'VintageID': 10961085,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=112440',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:07:16Z',
  'CreatedAt': '2021-01-20T20:15:23Z'},
 {'ID': 50098,
  'CompetitionID': 5,
  'VintageID': 10961085,
  'Edition': '2017',
  'Medal': 'Excellent',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://www.hachette-vins.com/guide-vins/les-vins/paul-goerg-extra-brut-absolu-2017/201721262/',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:48:07Z',
  'CreatedAt': '2021-01-15T17:46:33Z'},
 {'ID': 91823,
  'CompetitionID': 8,
  'VintageID': 10961085,
  'Edition': '2010',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://www.chardonnay-du-monde.com/wod/WebObjects/Result.woa/wa/res?mod=medaille&c=*&y=2010&co=CdM&m=Argent&lang=AG',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:58:30Z',
  'CreatedAt': '2021-01-16T05:20:56Z'},
 {'ID': 153095,
  'CompetitionID': 1,
  'VintageID': 10973445,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': '93',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2017/Wine/391721?name=Giulio%20Ferrari-Riserva%20del%20Fondatore%20Extra%20Brut-2005',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:13:58Z',
  'CreatedAt': '2018-08-06T23:49:16Z'},
 {'ID': 104057,
  'CompetitionID': 11,
  'VintageID': 10973445,
  'Edition': '2016',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.hkiwsc.com/result/detail/4550',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:01:35Z',
  'CreatedAt': '2018-08-14T22:04:45Z'},
 {'ID': 49069,
  'CompetitionID': 1,
  'VintageID': 11052019,
  'Edition': '2015',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2015/Wine/64670?name=Codorn%C3%ADu-Cuv%C3%A9e%20Barcelona%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:47:52Z',
  'CreatedAt': '2021-01-13T09:18:46Z'},
 {'ID': 118092,
  'CompetitionID': 1,
  'VintageID': 11052019,
  'Edition': '2016',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': '86',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2016/Wine/324866?name=Codorniu-Cuv%C3%A9e%20Barcelona%201872%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:05:10Z',
  'CreatedAt': '2021-01-21T09:46:10Z'},
 {'ID': 124521,
  'CompetitionID': 2,
  'VintageID': 11052019,
  'Edition': '2016',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=96916',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:06:46Z',
  'CreatedAt': '2021-01-20T20:14:56Z'},
 {'ID': 146938,
  'CompetitionID': 1,
  'VintageID': 11177619,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': '91',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2017/Wine/396544?name=Wynns-John%20Riddoch%20Cabernet%20Sauvignon-2013',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:12:18Z',
  'CreatedAt': '2018-03-23T13:08:59Z'},
 {'ID': 139157,
  'CompetitionID': 2,
  'VintageID': 11177619,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=111728',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:10:25Z',
  'CreatedAt': '2018-07-13T19:44:06Z'},
 {'ID': 10215,
  'CompetitionID': 4,
  'VintageID': 11177619,
  'Edition': '2016',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.iwsc.net/result/detail/75087',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:38:01Z',
  'CreatedAt': '2018-07-13T15:39:42Z'},
 {'ID': 36444,
  'CompetitionID': 4,
  'VintageID': 11177619,
  'Edition': '2017',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.iwsc.net/result/detail/83551',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:44:45Z',
  'CreatedAt': '2018-07-13T15:42:51Z'},
 {'ID': 10421,
  'CompetitionID': 1,
  'VintageID': 1119186,
  'Edition': '2012',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2012/Wine/39344?name=Mount%20Langi%20Ghiran-The%20Society%27s%20Exhibition%20Shiraz-2006',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:38:04Z',
  'CreatedAt': '2018-08-15T00:11:14Z'},
 {'ID': 130985,
  'CompetitionID': 2,
  'VintageID': 11216118,
  'Edition': '2017',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=111736',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:08:26Z',
  'CreatedAt': '2018-08-26T22:40:43Z'},
 {'ID': 43164,
  'CompetitionID': 4,
  'VintageID': 11216118,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.iwsc.net/result/detail/83533',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:46:25Z',
  'CreatedAt': '2018-03-15T12:28:16Z'},
 {'ID': 57073,
  'CompetitionID': 2,
  'VintageID': 11281412,
  'Edition': '2015',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=86519',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:49:51Z',
  'CreatedAt': '2018-08-14T21:52:56Z'},
 {'ID': 379,
  'CompetitionID': 2,
  'VintageID': 11281412,
  'Edition': '2014',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=74279',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:35:27Z',
  'CreatedAt': '2018-08-14T21:45:42Z'},
 {'ID': 68444,
  'CompetitionID': 2,
  'VintageID': 11434624,
  'Edition': '2015',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=86520',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:52:42Z',
  'CreatedAt': '2018-03-15T12:34:33Z'},
 {'ID': 2751,
  'CompetitionID': 2,
  'VintageID': 11434624,
  'Edition': '2014',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=74278',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:36:05Z',
  'CreatedAt': '2018-03-15T12:19:58Z'},
 {'ID': 125735,
  'CompetitionID': 1,
  'VintageID': 11487106,
  'Edition': '2016',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': '85',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2016/Wine/329848?name=Vasse%20Felix-Heytesbury%20Chardonnay-2014',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:07:08Z',
  'CreatedAt': '2018-03-19T12:46:41Z'},
 {'ID': 121323,
  'CompetitionID': 2,
  'VintageID': 11487106,
  'Edition': '2016',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=105204',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:05:58Z',
  'CreatedAt': '2018-03-19T12:45:32Z'},
 {'ID': 75192,
  'CompetitionID': 1,
  'VintageID': 1164784,
  'Edition': '2015',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2015/Wine/64838?name=Ar%20Lenoble-Blanc%20de%20Blancs%20Grand%20Cru%20Brut-2008',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:54:24Z',
  'CreatedAt': '2018-07-13T21:58:59Z'},
 {'ID': 51668,
  'CompetitionID': 2,
  'VintageID': 1164784,
  'Edition': '2015',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=88910',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:48:29Z',
  'CreatedAt': '2018-03-15T12:30:20Z'},
 {'ID': 92242,
  'CompetitionID': 9,
  'VintageID': 121343417,
  'Edition': '2017',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': '',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:58:37Z',
  'CreatedAt': '2021-01-16T03:57:39Z'},
 {'ID': 133381,
  'CompetitionID': 1,
  'VintageID': 12171276,
  'Edition': '2016',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': '86',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2016/Wine/325059?name=Albert%20Bichot-Hospices%20de%20Beaune%20Cuv%C3%A9e%20Albert%20Grivault%2C%20Charmes-2013',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:09:00Z',
  'CreatedAt': '2018-08-23T01:03:30Z'},
 {'ID': 19562,
  'CompetitionID': 4,
  'VintageID': 12265104,
  'Edition': '2016',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.iwsc.net/result/detail/75082',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:40:26Z',
  'CreatedAt': '2018-07-13T15:40:51Z'},
 {'ID': 24233,
  'CompetitionID': 4,
  'VintageID': 12265104,
  'Edition': '2017',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.iwsc.net/result/detail/83535',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:41:38Z',
  'CreatedAt': '2018-03-15T12:24:27Z'},
 {'ID': 89208,
  'CompetitionID': 7,
  'VintageID': 12265104,
  'Edition': '2015',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DAWA/2015/Wine/77472?name=Wolf%20Blass-Black%20Label%20Cabernet%20Sauvignon-Shiraz-2005',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:57:50Z',
  'CreatedAt': '2018-08-15T00:32:25Z'},
 {'ID': 28512,
  'CompetitionID': 2,
  'VintageID': 1227938,
  'Edition': '2014',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=70034',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:42:43Z',
  'CreatedAt': '2018-03-15T12:25:18Z'},
 {'ID': 102609,
  'CompetitionID': 7,
  'VintageID': 1227938,
  'Edition': '2017',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': '84',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DAWA/2017/Wine/406461?name=Bird%20In%20Hand-Nest%20Egg%20Cabernet%20Sauvignon-2009',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:01:14Z',
  'CreatedAt': '2018-03-15T12:41:51Z'},
 {'ID': 51875,
  'CompetitionID': 5,
  'VintageID': 12447467,
  'Edition': '2017',
  'Medal': 'Remarkable',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://www.hachette-vins.com/guide-vins/les-vins/dom-de-malarrode-quintessence-2014-2017/201705337/',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:48:33Z',
  'CreatedAt': '2018-08-18T17:05:08Z'},
 {'ID': 109385,
  'CompetitionID': 1,
  'VintageID': 12865935,
  'Edition': '2015',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2015/Wine/71334?name=Le%20Mesnil-Blanc%20de%20Blancs%20Grand%20Cru%20Brut-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:02:56Z',
  'CreatedAt': '2021-01-21T09:44:44Z'},
 {'ID': 145698,
  'CompetitionID': 1,
  'VintageID': 12865935,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': '91',
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2017/Wine/391613?name=Le%20Mesnil-Berry%20Bros.%20%26%20Rudd%20Blanc%20de%20Blancs%20Brut%20Grand%20Cru-NV',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:11:59Z',
  'CreatedAt': '2021-01-21T09:55:53Z'},
 {'ID': 115207,
  'CompetitionID': 2,
  'VintageID': 12865935,
  'Edition': '2016',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=101070',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:04:25Z',
  'CreatedAt': '2021-01-20T20:12:47Z'},
 {'ID': 137659,
  'CompetitionID': 2,
  'VintageID': 12865935,
  'Edition': '2017',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=109283',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:10:03Z',
  'CreatedAt': '2021-01-20T20:18:58Z'},
 {'ID': 123785,
  'CompetitionID': 2,
  'VintageID': 12918418,
  'Edition': '2016',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=97087',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:06:35Z',
  'CreatedAt': '2018-07-13T19:39:09Z'},
 {'ID': 5749,
  'CompetitionID': 1,
  'VintageID': 1291843,
  'Edition': '2012',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2012/Wine/41440?name=Torres-Grans%20Muralles-2008',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:36:50Z',
  'CreatedAt': '2018-03-15T12:20:35Z'},
 {'ID': 4015,
  'CompetitionID': 1,
  'VintageID': 1296621,
  'Edition': '2012',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2012/Wine/37908?name=Katnook%20Estate-Prodigy%20Shiraz-2008',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:36:24Z',
  'CreatedAt': '2018-03-15T12:20:13Z'},
 {'ID': 33129,
  'CompetitionID': 2,
  'VintageID': 13029367,
  'Edition': '2014',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'https://www.internationalwinechallenge.com/canopy/beverage_details.php?wid=65805',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:43:55Z',
  'CreatedAt': '2021-01-16T19:56:19Z'},
 {'ID': 83226,
  'CompetitionID': 5,
  'VintageID': 13044877,
  'Edition': '2017',
  'Medal': 'Commended',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://www.hachette-vins.com/guide-vins/les-vins/f-amp-r-miniere-cuvee-influence-vinifie-en-fut-de-chene-2017/201719397/',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:56:22Z',
  'CreatedAt': '2021-01-15T17:51:19Z'},
 {'ID': 19082,
  'CompetitionID': 1,
  'VintageID': 13062925,
  'Edition': '2012',
  'Medal': 'Bronze',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2012/Wine/42326?name=Wolf%20Blass-Black%20Label-2007',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:40:19Z',
  'CreatedAt': '2018-08-15T00:12:12Z'},
 {'ID': 3200,
  'CompetitionID': 1,
  'VintageID': 1320892,
  'Edition': '2012',
  'Medal': 'Silver',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://awards.decanter.com/DWWA/2012/Wine/42177?name=Wakefield%2FTaylors-St%20Andrews%20Shiraz-2006',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T12:36:11Z',
  'CreatedAt': '2018-07-13T21:51:11Z'},
 {'ID': 102347,
  'CompetitionID': 10,
  'VintageID': 13281708,
  'Edition': '2017',
  'Medal': 'Gold',
  'Trophy': None,
  'Score': None,
  'Visible': True,
  'URL': 'http://results.concoursmondial.com/result_popup.php?id=106562',
  'Origin': 0,
  'UserID': None,
  'UpdatedAt': '2022-10-19T13:01:10Z',
  'CreatedAt': '2021-01-12T19:47:13Z'},
 {'ID': 64022,
  'CompetitionID': 5,
  'VintageID': 13373510,

In [293]:
df_awards1 = pd.json_normalize(l, sep='_')
df_awards1 = df_awards1.drop_duplicates(subset="ID")
df_awards1

,ID,CompetitionID,VintageID,Edition,Medal,Trophy,Score,Visible,URL,Origin,UserID,UpdatedAt,CreatedAt
0,35171,1,10023048,2014,Silver,None,None,True,http://awards.decanter.com/DWWA/2014/Wine/5320...,0,NaN,2022-10-19T12:44:26Z,2021-01-13T09:15:58Z
1,57122,1,10023048,2015,Commended,None,None,True,http://awards.decanter.com/DWWA/2015/Wine/6712...,0,NaN,2022-10-19T12:49:52Z,2021-01-13T09:20:34Z
2,4175,4,10023048,2015,Silver,None,None,True,https://www.iwsc.net/result/detail/62445,0,NaN,2022-10-19T12:36:26Z,2021-01-15T17:33:33Z
3,87134,7,10023048,2015,Bronze,None,None,True,http://awards.decanter.com/DAWA/2015/Wine/7676...,0,NaN,2022-10-19T12:57:21Z,2021-01-13T09:28:33Z
4,93077,7,10023048,2017,Bronze,None,88,True,http://awards.decanter.com/DAWA/2017/Wine/4064...,0,NaN,2022-10-19T12:58:48Z,2021-01-13T09:29:57Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1581,94689,6,91756680,Summer Tasting 2017,Gold,None,None,True,https://www.meininger.de/en/wine/2016-fransola...,0,NaN,2022-10-19T12:59:12Z,2018-03-15T12:40:16Z
1582,27453,1,9611919,2014,Silver,None,None,True,http://awards.decanter.com/DWWA/2014/Wine/5396...,0,NaN,2022-10-19T12:42:27Z,2021-01-13T09:14:18Z
1583,36846,2,9611919,2014,Bronze,None,None,True,https://www.internationalwinechallenge.com/can...,0,NaN,2022-10-19T12:44:51Z,2021-01-16T19:56:50Z
1584,142435,1,98578275,2017,Gold,None,95,True,http://awards.decanter.com/DWWA/2017/Wine/3891...,0,NaN,2022-10-19T13:11:12Z,2018-03-23T13:06:24Z
1585,112948,3,98578275,2017,Bronze,None,None,True,http://winejudging.com/medal_winners_2017/awar...,0,NaN,2022-10-19T13:03:50Z,2018-03-19T12:43:27Z

In [294]:
# save table
df_awards1.to_csv(INTERIM_DATA / "vivino/awards1_df.csv", index=False)

In [295]:
l = df_round1["awards"]
l = [[el[i]["ID"] for i in range(len(el))] if el else np.nan for el in l]
l

[nan,
 nan,
 [35171, 57122, 4175, 87134, 93077],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [55799],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [154205, 129599, 105440],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [45476],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [62575],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [126238, 50098, 91823],
 [153095, 104057],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [49069, 118092, 124521],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [146938, 139157, 10215, 36444],
 nan,
 nan,
 nan,
 [10421],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [130985, 43164],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [57073, 379],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [68444, 2751],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [125735, 121323],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [75192, 51668],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [92242],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [133381],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [19562, 24233, 89208],
 nan,
 [28512, 102609],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [51875],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [109385, 145698, 115207, 137659],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [123785],
 [5749],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [4015],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [33129],
 nan,
 nan,
 nan,
 [83226],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [19082],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [3200],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [102347],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [64022],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [46527, 117915, 151872, 41926, 114008],
 nan,
 nan,
 nan,
 [23246],
 nan,
 nan,
 [119745, 118133],
 nan,
 nan,
 nan,
 nan,
 [41424, 106332, 117815, 145394, 32486],
 nan,
 nan,
 nan,
 [34588],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [56786],
 nan,
 nan,
 nan,
 nan,
 [10799],
 nan,
 nan,
 nan,
 nan,
 nan,
 [76097],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 [146961],
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...]

In [296]:
df_round1["awards"] = l
df_round1

,id,seo_name,name,statistics,certified_biodynamic,wine,description,awards,ratings_distribution,ranking,recommended_drinking_window,wine_facts,grape_composition,year,grapes,has_valid_ratings
0,100015094,chateau-mouton-rothschild-aile-d-argent-blanc-...,Château Mouton Rothschild Aile d'Argent Blanc ...,"{'status': 'Normal', 'ratings_count': 381, 'ra...",False,2284844,,NaN,"[3, 3, 67, 246, 62]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'oak_aged': 0, 'certified_bi...","{'17': 0, '18': 0}",2016,"[17, 18]",True
1,10013618,reynvaan-the-classic-estate-cabernet-sauvignon...,Reynvaan The Classic Estate Cabernet Sauvignon...,"{'status': 'BelowThreshold', 'ratings_count': ...",None,2369586,,NaN,"[0, 2, 8, 8, 3]",{'country': {'description': 'Rank within Unite...,"{'start_year': 2015, 'end_year': 2028, 'status...",{},{},2013,NaN,False
2,10023048,j-m-gremillet-blanc-de-blancs-brut-champagne-nv,Gremillet Blanc de Blancs Brut Champagne,"{'status': 'Normal', 'ratings_count': 486, 'ra...",None,2714706,,"[35171, 57122, 4175, 87134, 93077]","[5, 10, 161, 270, 40]",{'country': {'description': 'Rank within Franc...,"{'start_year': None, 'end_year': None, 'status...","{'alcohol': 12.5, 'residual_sugar_grams_per_li...",{'5': 100},N.V.,[5],True
3,10027177,deutz-blanc-de-blancs-brut-champagne-2013,Deutz Blanc de Blancs Brut Champagne 2013,"{'status': 'Normal', 'ratings_count': 373, 'ra...",None,1142211,,NaN,"[0, 2, 57, 274, 40]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2015, 'end_year': 2028, 'status...",{'alcohol': 12.5},{'5': 100},2013,[5],True
4,100451553,livon-selezione-anniversario-2014,Livon Selezione Anniversario 2014,"{'status': 'Normal', 'ratings_count': 25, 'rat...",None,4153013,,NaN,"[0, 0, 3, 19, 3]",{'country': {'description': 'Rank within Italy...,"{'start_year': 2016, 'end_year': 2024, 'status...",{'alcohol': 13.5},{},2014,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35141,99616661,chateau-du-haut-pick-sauternes-2014,Château du Haut Pick Sauternes 2014,"{'status': 'Normal', 'ratings_count': 42, 'rat...",None,1834572,,NaN,"[1, 2, 24, 11, 4]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2018, 'end_year': 2034, 'status...",{},{},2014,NaN,True
35142,9986182,domaine-perrot-minot-vignes-centenaires-nuits-...,Domaine Perrot-Minot Vignes Centenaires Nuits-...,"{'status': 'Normal', 'ratings_count': 43, 'rat...",None,2711130,,NaN,"[0, 1, 0, 31, 11]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2014, 'end_year': 2028, 'status...",{},{},2012,NaN,True
35143,99861,fr-chateau-pape-clement-pessac-leognan-grand-c...,Château Pape Clément Pessac-Léognan (Grand Cru...,"{'status': 'Normal', 'ratings_count': 1641, 'r...",None,82613,The grapes are initially sorted in the vineyar...,NaN,"[9, 13, 127, 1012, 480]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2011, 'end_year': 2026, 'status...","{'alcohol': 13.5, 'residual_sugar_grams_per_li...",{},2006,NaN,True
35144,99949,biondi-santi-brunello-di-montalcino-riserva-2001,Biondi-Santi Brunello di Montalcino Riserva 2001,"{'status': 'Normal', 'ratings_count': 154, 'ra...",None,82698,,NaN,"[0, 3, 9, 65, 77]",{'country': {'description': 'Rank within Italy...,"{'start_year': 2011, 'end_year': 2028, 'status...","{'alcohol': 14, 'contains_sulfites_allergens':...",{'16': 100},2001,[16],True
35145,9997820,domaine-cazes-muscat-de-rivesaltes-vin-doux-na...,Cazes Muscat de Rivesaltes Vin Doux Naturel 1991,"{'status': 'BelowThreshold', 'ratings_count': ...",None,20225,,NaN,"[0, 0, 0, 3, 1]",{'country': {'description': 'Rank within Franc...,"{'start_year': 2001, 'end_year': 2026, 'status...",{'contains_sulfites_allergens': True},{},1991,NaN,False

In [297]:
df_round1_wind = pd.json_normalize(df_round1['recommended_drinking_window'], sep='_').add_prefix("window_")
df_round1_wind

       window_start_year  window_end_year  window_status
0                 2018.0           2026.0            5.0
1                 2015.0           2028.0            5.0
2                    NaN              NaN            1.0
3                 2015.0           2028.0            5.0
4                 2016.0           2024.0            5.0
...                  ...              ...            ...
35141             2018.0           2034.0            5.0
35142             2014.0           2028.0            5.0
35143             2011.0           2026.0            5.0
35144             2011.0           2028.0            5.0
35145             2001.0           2026.0            5.0

[35146 rows x 3 columns]

In [298]:
df_round1 = pd.concat([df_round1.drop(columns='recommended_drinking_window'), df_round1_wind], axis = 1)

In [299]:
df_stats = pd.json_normalize(df_round1['statistics'].values, sep='_').add_prefix("stats_")
df_stats

,stats_status,stats_ratings_count,stats_ratings_average,stats_labels_count,stats_reviews_count
0,Normal,381,4.2,3397,148
1,BelowThreshold,21,0.0,168,5
2,Normal,486,3.9,4389,150
3,Normal,373,4.2,2100,123
4,Normal,25,4.1,91,9
...,...,...,...,...,...
35141,Normal,42,3.5,326,17
35142,Normal,43,4.5,362,17
35143,Normal,1641,4.4,14485,499
35144,Normal,154,4.6,1081,62
35145,BelowThreshold,4,0.0,40,2

In [300]:
df_round1 = pd.concat([df_round1.drop(columns='statistics'), df_stats], axis = 1)

In [306]:
df_round1.to_csv(INTERIM_DATA / "vivino/df_round1.csv", index=False)

---

In [190]:
# round 2 files parsing

In [212]:
with open(RAW_DATA / "vivino/all_merged_round2.json") as f:
    raw_js_wines = json.load(f)

In [213]:
raw_js_wines = raw_js_wines['vintage']

In [214]:
raw_filtered_wines = [{k: wine[k] for k in keep_keys} for wine in raw_js_wines]

In [215]:
with open(INTERIM_DATA / "vivino/filtered_wines_round2.json", "w") as f:
    json.dump(raw_filtered_wines, f, indent=2)

In [216]:
with open(INTERIM_DATA / "vivino/filtered_wines_round2.json") as f:
    raw_js_wines = json.load(f)

In [219]:
# parsing the data
df_round2 = pd.DataFrame(raw_js_wines)

In [221]:
grapes2 = df_round2['grapes'].values
grapes2 = [element[0] for element in grapes2 if element]
df_grapes2 = pd.DataFrame(grapes2)
df_grapes2 = df_grapes2.drop_duplicates()
df_grapes2

,id,name,seo_name,has_detailed_info,wines_count,parent_grape_id
0,16,Sangiovese,sangiovese,True,125094,NaN
1,5,Chardonnay,chardonnay,True,604208,NaN
2,43,Corvina,corvina,False,22300,NaN
3,14,Pinot Noir,pinot-noir,True,572334,NaN
6,167,Tinta de toro,tinta-de-toro,False,3803,19.0
...,...,...,...,...,...,...
3790,40,Alicante Bouschet,alicante-bouschet,False,30014,NaN
3956,159,Pecorino,pecorino,False,5526,NaN
4061,111,Procanico,procanico,False,675,1556.0
4063,155,Muscat Ottonel,muscat-ottonel,False,4451,NaN
4155,1686,Riesling Italico,riesling-italico,False,1519,588.0

In [222]:
df_grapes2.to_csv(INTERIM_DATA / "vivino/grapes2_df.csv", index=False)

In [224]:
l = df_round2['grapes'].values
l = [[el[i]["id"] for i in range(len(el))] if el else np.nan for el in l]
df_round2['grapes'] = l

In [ ]:
# table of wine (parent)
wine2 = df_round2["wine"].values
df_wines2 = pd.json_normalize(wine2, sep='_')
df_wines2 = df_wines2.drop_duplicates(subset="id")
df_wines2

,id,name,seo_name,type_id,vintage_type,is_natural,vintage_mask,review_status,rank,hidden,...,specialists_notes,style_region,style,style_region_background_image,style_image_location,winery_dashboard_url,winery_background_image_location,winery_background_image_variations_large,winery_background_image_variations_medium,winery_background_image_variations_small
0,2774081,Júlio Bastos Grande Reserva,julio-bastos-grande-reserva,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100045,Morey-Saint-Denis Premier Cru Clos de La Bussière,morey-saint-denis-premier-cru-clos-de-la-bussiere,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2695604,Mocenni Numero 89 Gran Selezione Chianti Classico,mocenni-numero-89-gran-selezione-chianti-classico,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1981762,Terroir Series (Terroir Selection) Chardonnay,terroir-series-terroir-selection-chardonnay,2,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2716483,Pietro Dal Cero Amarone della Valpolicella,pietro-dal-cero-amarone-della-valpolicella,1,0,False,"[2024, 2025]",2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755,2530402,La Casona de Arínzano,la-casona-de-arinzano,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,https://images.ctfassets.net/w1asd4g1aem0/4o5p...,NaN,NaN,NaN,NaN,NaN
9763,4136996,Vin de Days Rogue,vin-de-days-rogue,1,0,True,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9769,2581810,Zeltinger Sonnenuhr Riesling Auslese***,zeltinger-sonnenuhr-riesling-auslese,2,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9774,1101056,Brunello di Montalcino,brunello-di-montalcino,1,0,False,"[2021, 2022, 2023, 2024, 2025]",2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9779,1135897,Pinot Noir,pinot-noir,1,0,False,[2025],2,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
df_wines2.to_csv(INTERIM_DATA / "vivino/wines2_df.csv", index=False)

In [233]:
# split col wine
l = df_round2['wine']
l = [el["id"] if el else np.nan for el in l]
df_round2['wine'] = l

In [235]:

# rating distributions
rat2 = df_round2['ratings_distribution']
rat2 = [[e[str(i)] for i in range(1, 6)] for e in rat2]
df_round2['ratings_distribution'] = rat2

In [237]:
l = df_round2["awards"].values
l = [subel for el in l for subel in el if subel]
df_awards2 = pd.json_normalize(l, sep='_')
df_awards2 = df_awards2.drop_duplicates(subset="ID")
df_awards2

,ID,CompetitionID,VintageID,Edition,Medal,Trophy,Score,Visible,URL,Origin,UserID,UpdatedAt,CreatedAt
0,15851,4,10746401,2016,Silver,None,None,True,https://www.iwsc.net/result/detail/69152,0,NaN,2022-10-19T12:39:30Z,2018-08-18T16:52:11Z
1,8132,3,109615568,2014,Silver,None,None,True,http://winejudging.com/medal_winners_2014/awar...,0,NaN,2022-10-19T12:37:26Z,2021-01-12T19:48:16Z
2,37602,3,109615568,2015,Gold,None,None,True,http://winejudging.com/medal_winners_2015/awar...,0,NaN,2022-10-19T12:45:02Z,2021-01-12T19:53:56Z
3,29797,2,11011645,2014,Gold,None,None,True,https://www.internationalwinechallenge.com/can...,0,NaN,2022-10-19T12:43:04Z,2018-03-15T12:25:33Z
4,150795,1,11047499,2017,Bronze,None,88,True,http://awards.decanter.com/DWWA/2017/Wine/3946...,0,NaN,2022-10-19T13:13:22Z,2018-03-23T13:11:50Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,40812,2,8090422,2015,Gold,None,None,True,https://www.internationalwinechallenge.com/can...,0,NaN,2022-10-19T12:45:50Z,2018-03-15T12:27:46Z
161,20408,3,8295607,2015,Double Gold,None,None,True,http://winejudging.com/medal_winners_2015/awar...,0,NaN,2022-10-19T12:40:39Z,2018-03-15T12:23:38Z
162,136286,2,86869236,2017,Silver,None,None,True,https://www.internationalwinechallenge.com/can...,0,NaN,2022-10-19T13:09:43Z,2018-03-23T13:04:21Z
163,32245,4,86869236,2017,Bronze,None,None,True,https://www.iwsc.net/result/detail/77429,0,NaN,2022-10-19T12:43:41Z,2018-08-18T16:53:25Z
164,105675,1,8762411,2015,Gold,None,None,True,http://awards.decanter.com/DWWA/2015/Wine/6576...,0,NaN,2022-10-19T13:01:59Z,2018-03-19T12:41:23Z

In [250]:
df_awards2.to_csv(INTERIM_DATA / "vivino/df_awards2.csv", index=False)

In [ ]:
l = df_round2["awards"]
l = [[el[i]["ID"] for i in range(len(el))] if el else np.nan for el in l]
df_round2["awards"] = l

In [246]:
df_round2_wind = pd.json_normalize(df_round2['recommended_drinking_window'], sep='_').add_prefix("window_")
df_round2 = pd.concat([df_round2.drop(columns='recommended_drinking_window'), df_round2_wind], axis = 1)

In [ ]:
df_stats = pd.json_normalize(df_round2['statistics'].values, sep='_').add_prefix("stats_")
df_round2 = pd.concat([df_round2.drop(columns='statistics'), df_stats], axis = 1)

KeyError: 'statistics'

In [312]:
df_round2.to_csv(INTERIM_DATA / "vivino/df_round2.csv", index=False)

---

#### Fusion of the db

In [313]:
# test chekout prices
w1 = pd.read_csv(INTERIM_DATA / "vivino/df_round1.csv")
w2 = pd.read_csv(INTERIM_DATA / "vivino/df_round2.csv")

In [314]:
w = pd.concat([w1, w2])
w.to_csv(INTERIM_DATA / "vivino/df_all_wines.csv", index=False)

In [315]:
w1 = pd.read_csv(INTERIM_DATA / "vivino/awards1_df.csv")
w2 = pd.read_csv(INTERIM_DATA / "vivino/df_awards2.csv")
w = pd.concat([w1, w2])
w.to_csv(INTERIM_DATA / "vivino/df_all_awards.csv", index=False)

In [316]:
w1 = pd.read_csv(INTERIM_DATA / "vivino/grapes1_df.csv")
w2 = pd.read_csv(INTERIM_DATA / "vivino/grapes2_df.csv")
w = pd.concat([w1, w2])
w.to_csv(INTERIM_DATA / "vivino/df_all_grapes.csv", index=False)

In [317]:
w1 = pd.read_csv(INTERIM_DATA / "vivino/wines1_df.csv")
w2 = pd.read_csv(INTERIM_DATA / "vivino/wines2_df.csv")
w = pd.concat([w1, w2])
w.to_csv(INTERIM_DATA / "vivino/df_all_wines_parent.csv", index=False)

In [318]:
all_wines = pd.read_csv(INTERIM_DATA / "vivino/df_all_wines.csv")

In [323]:
all_wines['id'].values

array([100015094,  10013618,  10023048, ...,     99255,   9928081,
           99402])